---

- name: Upgrade packages
  apt: update_cache=yes
       upgrade=yes
  tags:
    - common-pkgs
    - common-pkgs-upgrade

- name: Install python-software-properties
  apt: pkg=python-software-properties
       state=latest
  tags:
    - common-pkgs
    - common-pkgs-pythonswprops

- name: Add repositories
  apt_repository: repo={{ item }}
                  state=present
  with_items:
    - '{{ repositories }}'
  tags:
    - common-pkgs
    - common-pkgs-repos

- name: Install
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - '{{ packages }}'
  tags:
    - common-pkgs
    - common-pkgs-install
